name: CI/CD - dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}
      sha_tag: ${{ steps.meta.outputs.sha_tag }}
    steps:
      - uses: actions/checkout@v4

      # Habilita Buildx (driver docker-container) e resolve o problema de cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image meta
        id: meta
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/mundo-da-lua-home"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "sha_tag=dev-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Usa cache GHA (evita o erro e acelera builds)
      - name: Build & Push (dev + dev-$GITHUB_SHA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:dev
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.sha_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Prepare SSH key & known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_CERT }}" > ~/.ssh/gha_deploy
          chmod 600 ~/.ssh/gha_deploy
          if [ -n "${{ secrets.KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          fi

      - name: Set image in Kubernetes (microk8s)
        env:
          HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USER }}
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          SHA_TAG: ${{ needs.build-and-push.outputs.sha_tag }}
        run: |
          ssh -i ~/.ssh/gha_deploy -o StrictHostKeyChecking=yes -p "$PORT" "$USER@$HOST" \
            "set -euo pipefail; \
             if command -v microk8s >/dev/null 2>&1; then CMD='microk8s kubectl'; else CMD='kubectl'; fi; \
             NS='mundo-da-lua';DEPLOY='mundo-da-lua-home'; CONTAINER='mundo-da-lua-home'; \
             \$CMD set image deployment/\$DEPLOY \$CONTAINER=${IMAGE}:${SHA_TAG} --record; \
             \$CMD rollout status deployment/\$DEPLOY --timeout=120s; \
             \$CMD get pods -l app=\$CONTAINER -o wide --no-headers | head -n 5 \
            "
